# Generated by Django 5.0.7 on 2024-08-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cloud_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
