# Generated by Django 5.0.7 on 2024-08-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_cloud_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='event',
        ),
    ]
